//
// Created by 48791 on 19.01.2023.
//

#ifndef MINIPROJEKT_PROBLEMFILEOPENINGOUTCOME_H
#define MINIPROJEKT_PROBLEMFILEOPENINGOUTCOME_H

enum class ProblemFileOpeningOutcome
{
    SUCCESS,
    ERROR_FILE_NOT_FOUND,
    ERROR_FILE_INCORRECT_FORMAT,
    ERROR_INCORRECT_DATA
};

#endif //MINIPROJEKT_PROBLEMFILEOPENINGOUTCOME_H
